name: sweepdemo
project: MLOps_course
entity: minra-technical-university-of-denmark

method: random
metric:
  goal: minimize
  name: val_loss

parameters:
  training.lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  training.batch_size:
    values: [16, 32, 64]
  training.epochs:
    values: [5, 10, 15]

run_cap: 10

command:
  - uv
  - run
  - train
  - ${args_no_hyphens}
